# Generated by Django 4.2 on 2023-08-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisinp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('FREETEXT', 'Freetext'), ('MULTI', 'Multiple Choice'), ('SO', 'Single Option Choice'), ('MT', 'Multiple Choice + Free Text'), ('ST', 'Single Choice + Free Text'), ('CL', 'Countries list'), ('DATE', 'Date picker')], default='FREETEXT', max_length=10),
        ),
    ]
