# Generated by Django 4.2 on 2023-08-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisinp', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='accronym',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
